# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mydesign.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Main(object):
    def setupUi(self, Main):
        #настройки главного окна и бэкэнда
        Main.setObjectName("Main")
        Main.resize(800, 600)
        Main.setStyleSheet("background-color:rgb(255, 255, 255);")
        ##################################################################
        #размеры главного окна
        self.main_wg = QtWidgets.QWidget(Main)
        self.main_wg.setMinimumSize(QtCore.QSize(400, 400))
        self.main_wg.setMaximumSize(QtCore.QSize(1600, 1600))
        self.main_wg.setBaseSize(QtCore.QSize(800, 800))
        self.main_wg.setStyleSheet("background-color:rgb(255, 255, 255);")
        self.main_wg.setObjectName("main_wg")
        ##################################################################
        #кнопка отправки писем или письма
        self.mail_send_but = QtWidgets.QPushButton(self.main_wg)
        self.mail_send_but.setGeometry(QtCore.QRect(10, 440, 420, 110))
        self.mail_send_but.setMinimumSize(QtCore.QSize(210, 55))
        self.mail_send_but.setMaximumSize(QtCore.QSize(840, 220))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.mail_send_but.setFont(font)
        self.mail_send_but.setStyleSheet("border: 3px solid black;background-color:rgb(255, 255, 255);")
        self.mail_send_but.setObjectName("mail_send_but")
        ##################################################################
        #количество сообщений
        self.volum_edit = QtWidgets.QLineEdit(self.main_wg)
        self.volum_edit.setGeometry(QtCore.QRect(10, 380, 260, 40))
        self.volum_edit.setMinimumSize(QtCore.QSize(130, 20))
        self.volum_edit.setMaximumSize(QtCore.QSize(520, 80))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.volum_edit.setFont(font)
        self.volum_edit.setStyleSheet("background-color: rgb(0, 255, 255);border: 2px solid black;")
        self.volum_edit.setObjectName("volum_edit")
        ##################################################################
        #надпись "Количество"
        self.vlm_lbl = QtWidgets.QLabel(self.main_wg)
        self.vlm_lbl.setGeometry(QtCore.QRect(10, 310, 260, 50))
        self.vlm_lbl.setMinimumSize(QtCore.QSize(130, 25))
        self.vlm_lbl.setMaximumSize(QtCore.QSize(520, 100))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.vlm_lbl.setFont(font)
        self.vlm_lbl.setStyleSheet("background-color: rgb(0, 255, 255);border: 2px solid black;")
        self.vlm_lbl.setObjectName("vlm_lbl")
        ##################################################################
        #надпись "Отправитель"
        self.progr_name = QtWidgets.QLabel(self.main_wg)
        self.progr_name.setGeometry(QtCore.QRect(200, 0, 350, 50))
        self.progr_name.setMinimumSize(QtCore.QSize(175, 25))
        self.progr_name.setMaximumSize(QtCore.QSize(700, 100))
        font = QtGui.QFont()
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        self.progr_name.setFont(font)
        self.progr_name.setStyleSheet("border: 2px solid black;")
        self.progr_name.setObjectName("progr_name")
        ##################################################################
        #поле ввода пороля
        self.pus_us_edit = QtWidgets.QLineEdit(self.main_wg)
        self.pus_us_edit.setGeometry(QtCore.QRect(600, 100, 180, 30))
        self.pus_us_edit.setMinimumSize(QtCore.QSize(90, 15))
        self.pus_us_edit.setMaximumSize(QtCore.QSize(360, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pus_us_edit.setFont(font)
        self.pus_us_edit.setStyleSheet("background-color:rgb(85, 85, 255);border: 2px solid black;")
        self.pus_us_edit.setText("")
        self.pus_us_edit.setObjectName("pus_us_edit")
        ##################################################################
        #ввод куда отправлять письма
        self.to_edit = QtWidgets.QLineEdit(self.main_wg)
        self.to_edit.setGeometry(QtCore.QRect(450, 320, 240, 30))
        self.to_edit.setMinimumSize(QtCore.QSize(120, 15))
        self.to_edit.setMaximumSize(QtCore.QSize(480, 60))
        self.to_edit.setStyleSheet("background-color: rgb(255, 170, 255);border: 2px solid black;")
        self.to_edit.setObjectName("to_edit")
        ##################################################################
        #надпись "Куда отправлять"
        self.to_lbl = QtWidgets.QLabel(self.main_wg)
        self.to_lbl.setGeometry(QtCore.QRect(320, 320, 120, 30))
        self.to_lbl.setMinimumSize(QtCore.QSize(60, 15))
        self.to_lbl.setMaximumSize(QtCore.QSize(240, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.to_lbl.setFont(font)
        self.to_lbl.setStyleSheet("background-color: rgb(255, 170, 255);border: 2px solid black;")
        self.to_lbl.setObjectName("to_lbl")
        ##################################################################
        # надпись "Ваши данные"
        self.user_dt_lbl = QtWidgets.QLabel(self.main_wg)
        self.user_dt_lbl.setGeometry(QtCore.QRect(560, 20, 160, 40))
        self.user_dt_lbl.setMinimumSize(QtCore.QSize(80, 20))
        self.user_dt_lbl.setMaximumSize(QtCore.QSize(320, 80))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.user_dt_lbl.setFont(font)
        self.user_dt_lbl.setStyleSheet("background-color:rgb(85, 85, 255);border: 2px solid black;")
        self.user_dt_lbl.setObjectName("user_dt_lbl")
        ##################################################################
        #поле ввода логина почты
        self.log_us_edit = QtWidgets.QLineEdit(self.main_wg)
        self.log_us_edit.setGeometry(QtCore.QRect(410, 100, 180, 30))
        self.log_us_edit.setMinimumSize(QtCore.QSize(90, 15))
        self.log_us_edit.setMaximumSize(QtCore.QSize(360, 60))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.log_us_edit.setFont(font)
        self.log_us_edit.setStyleSheet("background-color:rgb(85, 85, 255);border: 2px solid black;")
        self.log_us_edit.setText("")
        self.log_us_edit.setObjectName("log_us_edit")
        ##################################################################
        #Поле ввода сообщения
        self.msg_txt_edit = QtWidgets.QTextEdit(self.main_wg)
        self.msg_txt_edit.setGeometry(QtCore.QRect(10, 130, 360, 170))
        self.msg_txt_edit.setMinimumSize(QtCore.QSize(180, 85))
        self.msg_txt_edit.setMaximumSize(QtCore.QSize(720, 340))
        self.msg_txt_edit.setStyleSheet("background-color:rgb(85, 255, 127);border: 2px solid black;")
        self.msg_txt_edit.setObjectName("msg_txt_edit")
        ##################################################################
        # надпись "Пороль"
        self.pus_lbl = QtWidgets.QLabel(self.main_wg)
        self.pus_lbl.setGeometry(QtCore.QRect(650, 70, 80, 25))
        self.pus_lbl.setMinimumSize(QtCore.QSize(40, 12))
        self.pus_lbl.setMaximumSize(QtCore.QSize(160, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pus_lbl.setFont(font)
        self.pus_lbl.setStyleSheet("background-color:rgb(85, 85, 255);border: 2px solid black;")
        self.pus_lbl.setObjectName("pus_lbl")
        ##################################################################
        # надпись "Логин"
        self.log_lbl = QtWidgets.QLabel(self.main_wg)
        self.log_lbl.setGeometry(QtCore.QRect(460, 70, 70, 25))
        self.log_lbl.setMinimumSize(QtCore.QSize(35, 12))
        self.log_lbl.setMaximumSize(QtCore.QSize(140, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.log_lbl.setFont(font)
        self.log_lbl.setStyleSheet("background-color:rgb(85, 85, 255);border: 2px solid black;")
        self.log_lbl.setObjectName("log_lbl")
        ##################################################################
        # надпись "Текст сообщения"
        self.msg_txt_lbl = QtWidgets.QLabel(self.main_wg)
        self.msg_txt_lbl.setGeometry(QtCore.QRect(10, 70, 280, 50))
        self.msg_txt_lbl.setMinimumSize(QtCore.QSize(140, 25))
        self.msg_txt_lbl.setMaximumSize(QtCore.QSize(560, 100))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.msg_txt_lbl.setFont(font)
        self.msg_txt_lbl.setStyleSheet("background-color:rgb(85, 255, 127);border: 2px solid black;")
        self.msg_txt_lbl.setObjectName("msg_txt_lbl")
        ##################################################################
        # почты с которых отправлять письма
        self.area_us_dt = QtWidgets.QScrollArea(self.main_wg)
        self.area_us_dt.setGeometry(QtCore.QRect(410, 140, 370, 150))
        self.area_us_dt.setMinimumSize(QtCore.QSize(185, 75))
        self.area_us_dt.setMaximumSize(QtCore.QSize(740, 300))
        self.area_us_dt.setStyleSheet("background-color:rgb(0, 255, 255);border: 2px solid black;")
        self.area_us_dt.setWidgetResizable(True)
        self.area_us_dt.setObjectName("area_us_dt")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 366, 146))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.area_us_dt.setWidget(self.scrollAreaWidgetContents)
        ##################################################################
        #почты куда отправлять письма
        self.area_to = QtWidgets.QScrollArea(self.main_wg)
        self.area_to.setGeometry(QtCore.QRect(440, 370, 340, 170))
        self.area_to.setMinimumSize(QtCore.QSize(170, 85))
        self.area_to.setMaximumSize(QtCore.QSize(680, 340))
        self.area_to.setStyleSheet("background-color:rgb(255, 170, 255);border: 2px solid black;")
        self.area_to.setWidgetResizable(True)
        self.area_to.setObjectName("area_to")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 336, 166))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.area_to.setWidget(self.scrollAreaWidgetContents_2)
        ##################################################################
        #кнопка добавить почты куда отправлять письмо
        self.add_to_but = QtWidgets.QPushButton(self.main_wg)
        self.add_to_but.setGeometry(QtCore.QRect(700, 320, 80, 30))
        self.add_to_but.setMinimumSize(QtCore.QSize(40, 15))
        self.add_to_but.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.add_to_but.setFont(font)
        self.add_to_but.setStyleSheet("background-color: rgb(255, 170, 255);border: 2px solid black;")
        self.add_to_but.setObjectName("add_to_but")
        ##################################################################
        #кнопка добавления юзер данных
        self.add_us_dt_but = QtWidgets.QPushButton(self.main_wg)
        self.add_us_dt_but.setGeometry(QtCore.QRect(550, 70, 80, 30))
        self.add_us_dt_but.setMinimumSize(QtCore.QSize(40, 15))
        self.add_us_dt_but.setMaximumSize(QtCore.QSize(160, 60))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.add_us_dt_but.setFont(font)
        self.add_us_dt_but.setStyleSheet("border: 2px solid black;background-color:rgb(85, 85, 255);border: 2px solid black;")
        self.add_us_dt_but.setObjectName("add_us_dt_but")
        ##################################################################
        Main.setCentralWidget(self.main_wg)
        self.menubar = QtWidgets.QMenuBar(Main)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        Main.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Main)
        self.statusbar.setObjectName("statusbar")
        Main.setStatusBar(self.statusbar)

        self.retranslateUi(Main)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Sender"))
        self.mail_send_but.setText(_translate("Main", "Начать отправление"))
        self.vlm_lbl.setText(_translate("Main", "Количество"))
        self.progr_name.setText(_translate("Main", "Отправитель"))
        self.to_lbl.setText(_translate("Main", "Куда отправлять"))
        self.user_dt_lbl.setText(_translate("Main", "Ваши данные"))
        self.pus_lbl.setText(_translate("Main", "Пороль"))
        self.log_lbl.setText(_translate("Main", "Логин"))
        self.msg_txt_lbl.setText(_translate("Main", "Сообщение"))
        self.add_to_but.setText(_translate("Main", "Добавить"))
        self.add_us_dt_but.setText(_translate("Main", "Добавить"))
